{{- if (include "project.createConfigMap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project.configMapName" . }}
  labels: {{- include "project.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{- if ne $k "existingName"}}
  {{ $k | quote }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end -}}
