{{- if (include "project.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project.secretName" . }}
  labels: {{- include "project.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.secret }}
  {{- if ne $k "existingName"}}
  {{ $k | quote }}: {{ $v | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end -}}